### ISSUE TITLE
USF recon lack range marker

### ISSUE THREAD

**Issue by Stoklomolvi** [Stoklomolvi/Spearhead-Public#2]
**Game version:** Current official patch
**Summary:** USF recon lack range marker
**Way to reproduce it:** From Hq order a recon team
**Expected outcome:** USF recons having range marker just as other snipers and recon team
**Actual outcome:** USF recons lack it, like they would lack DMR

---
**Additional information:** It is borderline impossible to use them well like other recons squads as you don't see their range.
**Attachments:** N/A

**Reporter:** Discord user SzabóImi#2171

**Comment by Pariah919** [comment]
**GAME VERSION:** 1.1.5

Testing shows that scouts no longer have DMRs or even the ability to pick up slot items anymore, so this bug is likely deprecated and can be closed.

![image](https://user-images.githubusercontent.com/46353991/217952966-f28e62f7-22f7-4092-9d7c-25abc14666fd.png)
![image](https://user-images.githubusercontent.com/46353991/217953008-6dc93a6f-6366-4d04-951a-5ec293bf2dc0.png)
![image](https://user-images.githubusercontent.com/46353991/217953041-71efec8e-e56e-4b5a-aa63-81a59d6df44e.png)
![image](https://user-images.githubusercontent.com/46353991/217953095-876b8a2c-abd2-4125-ba88-2845fbbea692.png)

**Comment by RalphRoberts** [comment]
COnfirming that recon teams no longer have DMRs and thus this issue has been fixed.
