### ISSUE TITLE
Command tank Crews Spawning dismounted

### ISSUE THREAD

**Issue by Stoklomolvi** [Stoklomolvi/Spearhead-Public#47]
**Game Version**: Stoklomolvi
**Summary of Bug:** Command tank Crews Spawning dismounted
**Steps to Reproduce:**
1) Go to US or Commonwealth Tank Doctrines
2) Spawn a commander that is supposed to spawn with a vehicle

**Expected Outcome:** The squad spawns inside their command vehicle.
**Actual Outcome:** Squad spawns on foot without command vehicle.

---
**Additional Information:**: AI spawns the command crews correctly, within their vehicles and putting the players at a disadvantage.
**Attachments:** ![See attached screenshot](https://media.discordapp.net/attachments/770937541855412254/776445697779564584/unknown.png)

**Reporter:** Discord user Argos#8450

**Comment by 321nick** [comment]
iirc, i think its intentional. for US armor atleast, you can call in the command squad without the tank, when you have the building selected, and if you want the command squad with the tank you use the ability on the upper row of commander abilities. i think its the same here, from what i can see in the screenshot none of the abilities in the upper row of commander abilities were recently used so i think he called in the squad from the platoon command post, which only brings in the squad without the tank at a reduced price.

**Comment by Stoklomolvi** [comment]
I have not reviewed this report yet, but what the reporter is claiming is that he _is_ using the command bar abilities, and he is _still_ getting the infantry version. If that is the case, then it is a bug, but I have not confirmed this bug yet.

**Comment by Stoklomolvi** [comment]
Should have been fixed by v1.1.0.
